services:
  - type: static
    name: nexfit-frontend
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://afffyfsmcvphrhbtxrgt.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmZmZ5ZnNtY3ZwaHJoYnR4cmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcwNjU1NDYsImV4cCI6MjA4MjY0MTU0Nn0.cpLjvUADTJxzdr0MGIZFai_zYHPbnaU2P1I-EyDoqnw
      - key: VITE_RAPIDAPI_KEY
        fromContext: RAPIDAPI_KEY
      - key: VITE_VAPID_PUBLIC_KEY
        fromContext: VAPID_PUBLIC_KEY
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
